version: '3.7'
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:14.2-alpine
    volumes:
      - ./data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=innoter
      - POSTGRES_PASSWORD=innoter
      - POSTGRES_DB=innoter_dev
    ports:
      - 5432
volumes:
  postgres_data: