version: '3.9'
services:
  web:
    container_name: web
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
      - worker

  db:
    container_name: db
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_HOST=postgres
    ports:
      - "5438:5432"


  worker:
    container_name: celery_worker
    build:
      context: .
    depends_on:
      - rabbitmq
      - db
    command: celery -A innoter worker -l info

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.9-alpine
    restart: always

volumes:
  postgres_data: